# Generated by Django 4.1.7 on 2023-04-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='categoryThrough',
        ),
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='postThrough',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_ru',
        ),
        migrations.DeleteModel(
            name='PostCategory_en_us',
        ),
        migrations.DeleteModel(
            name='PostCategory_ru',
        ),
    ]
